#!/bin/sh --

#http://d.hatena.ne.jp/hirochachacha/20111004/1317715093

set -e

echo ""
echo "START POST-MERGE HOOK"
echo ""

HOOK_DIR=`dirname $0`      #git_hooks directory
PROC_DIR="$HOOK_DIR/../.." #vimproc directory

case `uname -s` in
  Darwin)
    MAKE_FILE='make_mac.mak'
    PROC_FILE='proc.so'
    ;;
  Linux)
    MAKE_FILE='make_gcc.mak'
    PROC_FILE='proc.so'
    ;;
  FreeBSD)
    MAKE_FILE='make_gcc.mak'
    PROC_FILE='proc.so'
    ;;
  CYGWIN*)
    MAKE_FILE='make_cygwin.mak'
    PROC_FILE='proc_cygwin.dll'
    ;;
  *)
    echo "This type of OS is not supported"
    exit 1
    ;;
esac


cd $PROC_DIR

if [ -f autoload/$PROC_FILE ]; then
  echo "deleting previous $PROC_FILE ..."
  rm autoload/$PROC_FILE
  echo "done"
  echo ""
fi

echo "compiling $PROC_FILE ..."
make -f $MAKE_FILE
echo "done"
echo ""

echo "vimproc: build success!"
echo ""

echo "END POST-MERGE HOOK"#!/bin/sh --
set -e

echo ""
echo "START POST-MERGE HOOK"
echo ""

HOOK_DIR=`dirname $0`      #git_hooks directory
PROC_DIR="$HOOK_DIR/../.." #vimproc directory

case `uname -s` in
  Darwin)
    MAKE_FILE='make_mac.mak'
    PROC_FILE='proc.so'
    ;;
  Linux)
    MAKE_FILE='make_gcc.mak'
    PROC_FILE='proc.so'
    ;;
  FreeBSD)
    MAKE_FILE='make_gcc.mak'
    PROC_FILE='proc.so'
    ;;
  CYGWIN*)
    MAKE_FILE='make_cygwin.mak'
    PROC_FILE='proc_cygwin.dll'
    ;;
  *)
    echo "This type of OS is not supported"
    exit 1
    ;;
esac


cd $PROC_DIR

if [ -f autoload/$PROC_FILE ]; then
  echo "deleting previous $PROC_FILE ..."
  rm autoload/$PROC_FILE
  echo "done"
  echo ""
fi

echo "compiling $PROC_FILE ..."
make -f $MAKE_FILE
echo "done"
echo ""

echo "vimproc: build success!"
echo ""

echo "END POST-MERGE HOOK"
